In [2]:
# Importing librairies
import pandas as pd
from datetime import datetime
from sqlalchemy import create_engine, Column, Float, Integer, String, ForeignKey
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

In [3]:
df = pd.read_csv("../Transform/weather_data_transformed.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1488 entries, 0 to 1487
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   latitude              1488 non-null   float64
 1   longitude             1488 non-null   float64
 2   date                  1488 non-null   object
 3   time_of_day           1488 non-null   object
 4   temperature_2m        1488 non-null   float64
 5   relative_humidity_2m  1488 non-null   float64
 6   precipitation         1488 non-null   float64
 7   wind_speed_10m        1488 non-null   float64
 8   weather_code          1488 non-null   float64
 9   location              1488 non-null   object
 10  heat_index            1488 non-null   float64
 11  is_raining            1488 non-null   int64
dtypes: float64(8), int64(1), object(3)
memory usage: 139.6+ KB

In [4]:
df

,latitude,longitude,date,time_of_day,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,weather_code,location,heat_index,is_raining
0,43.2965,5.3698,2025-02-25,Night,-1.339673,0.018646,0.085135,0.542909,0.0,Marseille 02,-0.951896,1
1,43.2965,5.3698,2025-02-25,Morning,-1.500753,0.101450,0.085135,0.547789,0.0,Marseille 02,-1.042330,1
2,43.2965,5.3698,2025-02-25,Afternoon,-1.346172,0.123200,0.085135,0.542316,0.0,Marseille 02,-0.955544,1
3,43.2965,5.3698,2025-02-25,Evening,-1.164595,0.032979,0.085135,0.536627,0.0,Marseille 02,-0.853602,1
4,43.2965,5.3698,2025-02-26,Night,-1.328588,0.014805,0.085135,0.542530,0.0,Marseille 02,-0.945672,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1483,48.8566,2.3522,2025-05-29,Evening,1.976579,-0.926833,-0.239521,-0.347950,0.0,Paris,2.734410,0
1484,48.8566,2.3522,2025-05-30,Night,0.847264,0.952639,-0.239521,-1.506526,0.0,Paris,0.275907,0
1485,48.8566,2.3522,2025-05-30,Morning,0.888834,0.802281,-0.239521,-1.180385,0.0,Paris,0.299245,0
1486,48.8566,2.3522,2025-05-30,Afternoon,2.828761,-1.270507,-0.239521,-0.686515,0.0,Paris,3.007469,0
1487,48.8566,2.3522,2025-05-30,Evening,3.112821,-1.689361,-0.239521,-0.745531,1.0,Paris,2.916644,0

In [5]:
Base = declarative_base()

C:\Users\HP\AppData\Local\Temp\ipykernel_520\4196137762.py:1: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

# Creating Class for table

In [6]:
# Table 1: Location
class Location(Base):
    __tablename__ = 'location'
    id = Column(Integer, primary_key=True)
    latitude = Column(Float)
    longitude = Column(Float)
    location_name = Column(String)

    weather_data = relationship("WeatherMeasurement", back_populates="location")

In [7]:
# Table 2: Time
class Time(Base):
    __tablename__ = 'time'
    id = Column(Integer, primary_key=True)
    date = Column(String)
    time_of_day = Column(String)

    weather_data = relationship("WeatherMeasurement", back_populates="time")

In [8]:
# Table 3: WeatherMeasurement
class WeatherMeasurement(Base):
    __tablename__ = 'weather_measurement'
    id = Column(Integer, primary_key=True)
    
    location_id = Column(Integer, ForeignKey('location.id'))
    time_id = Column(Integer, ForeignKey('time.id'))
    
    temperature_2m = Column(Float)
    relative_humidity_2m = Column(Float)
    precipitation = Column(Float)
    wind_speed_10m = Column(Float)
    weather_code = Column(Float)
    heat_index = Column(Float)
    is_raining = Column(Integer)

    location = relationship("Location", back_populates="weather_data")
    time = relationship("Time", back_populates="weather_data")

# Creating SQLite Database and Inserting Data

In [9]:
# Creation database
engine = create_engine('sqlite:///weather_SQLiteDatabase.db')
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

In [10]:
# Caches to avoid duplicates
location_cache = {}
time_cache = {}

In [11]:
for _, row in df.iterrows():
    # Location
    loc_key = (row['latitude'], row['longitude'], row['location'])
    if loc_key not in location_cache:
        loc = Location(latitude=row['latitude'], longitude=row['longitude'], location_name=row['location'])
        session.add(loc)
        session.flush()  # pour obtenir loc.id
        location_cache[loc_key] = loc.id
    location_id = location_cache[loc_key]

    # Time
    time_key = (row['date'], row['time_of_day'])
    if time_key not in time_cache:
        time = Time(date=row['date'], time_of_day=row['time_of_day'])
        session.add(time)
        session.flush()
        time_cache[time_key] = time.id
    time_id = time_cache[time_key]

    # WeatherMeasurement
    weather = WeatherMeasurement(
        location_id=location_id,
        time_id=time_id,
        temperature_2m=row['temperature_2m'],
        relative_humidity_2m=row['relative_humidity_2m'],
        precipitation=row['precipitation'],
        wind_speed_10m=row['wind_speed_10m'],
        weather_code=row['weather_code'],
        heat_index=row['heat_index'],
        is_raining=row['is_raining']
    )
    session.add(weather)

In [12]:
# Commit changes in database
session.commit()

# Dislaying some records

In [13]:
# Retrieving 5 records in table WeatherMeasurement
results = session.query(WeatherMeasurement).limit(5).all()

for measurement in results:
    print("---")
    print(f"Date: {measurement.time.date} {measurement.time.time_of_day}")
    print(f"Location: {measurement.location.location_name} "
          f"({measurement.location.latitude}, {measurement.location.longitude})")
    print(f"Temperature: {measurement.temperature_2m} Â°C")
    print(f"Humidity: {measurement.relative_humidity_2m} %")
    print(f"Precipitation: {measurement.precipitation} mm")
    print(f"Wind Speed: {measurement.wind_speed_10m} m/s")
    print(f"Weather Code: {measurement.weather_code}")
    print(f"Heat Index: {measurement.heat_index} Â°C")
    print(f"Is Raining: {'Yes' if measurement.is_raining else 'No'}")

---
Date: 2025-02-25 Night
Location: Marseille 02 (43.2965, 5.3698)
Temperature: -1.339672945509672 Â°C
Humidity: 0.0186459508451261 %
Precipitation: 0.085135318511375 mm
Wind Speed: 0.5429090976884772 m/s
Weather Code: 0.0
Heat Index: -0.9518955954129144 Â°C
Is Raining: Yes
---
Date: 2025-02-25 Morning
Location: Marseille 02 (43.2965, 5.3698)
Temperature: -1.5007529202816623 Â°C
Humidity: 0.1014504082428737 %
Precipitation: 0.0851353431218922 mm
Wind Speed: 0.5477888998482531 m/s
Weather Code: 0.0
Heat Index: -1.0423300073847397 Â°C
Is Raining: Yes
---
Date: 2025-02-25 Afternoon
Location: Marseille 02 (43.2965, 5.3698)
Temperature: -1.3461719877792748 Â°C
Humidity: 0.1231998136895461 %
Precipitation: 0.085135365638257 mm
Wind Speed: 0.5423161689066677 m/s
Weather Code: 0.0
Heat Index: -0.9555443237347528 Â°C
Is Raining: Yes
---
Date: 2025-02-25 Evening
Location: Marseille 02 (43.2965, 5.3698)
Temperature: -1.1645946827246725 Â°C
Humidity: 0.0329794686236698 %
Precipitation: 0.085135376729726 mm
Wind Speed: 0.53662698776711 m/s
Weather Code: 0.0
Heat Index: -0.8536021870210767 Â°C
Is Raining: Yes
---
Date: 2025-02-26 Night
Location: Marseille 02 (43.2965, 5.3698)
Temperature: -1.3285880087210429 Â°C
Humidity: 0.0148047381314186 %
Precipitation: 0.0851353866108153 mm
Wind Speed: 0.5425296408871031 m/s
Weather Code: 0.0
Heat Index: -0.9456722287800134 Â°C
Is Raining: Yes

In [14]:
# Commit
session.close()